services:
  mongo:
    # build:
    #   context: db
    #   target: DB
    image: "mongo:7.0-rc"
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
    networks:
      - backend
  web:
    build:
      context: ./
      target: builder
    ports:
      - '5000:5000'
    networks:
      - backend
    environment:
      WAIT_HOST: mongo:27017
    depends_on:
      - mongo

networks:
  backend: 
    driver: bridge
