apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-water
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-water
            image: yuko29/crawling-water:v1
            args:
            - /bin/sh
            - -c
            - python crawling_water.py
          restartPolicy: OnFailure