apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
spec:
  selector:
    app: flaskapp
  ports:
    - port: 8000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: meteorological-center-web
          image: meteorological-center-web:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Never