apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: meteorological-center-web
          image: yuko29/meteorological-center-web:v1
          ports:
            - containerPort: 5000
          imagePullPolicy: ifNotPresent